# Generated by Django 5.2 on 2025-04-30 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=200, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('niveau_etudes', models.CharField(choices=[('Bac', 'Baccalauréat'), ('Bac+1', 'Bac +1'), ('Bac+2', 'Bac +2'), ('Bac+3', 'Bac +3'), ('Bac+4', 'Bac +4')], max_length=10, verbose_name="Niveau d'études")),
                ('etablissement_origine', models.CharField(max_length=200, verbose_name="Établissement d'origine")),
                ('concours_souhaite', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2, verbose_name='Concours souhaité')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('extrait_naissance', models.FileField(upload_to='extraits/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Extrait de naissance (PDF)')),
                ('certificat', models.FileField(upload_to='certificats/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Certificat de scolarité ou diplôme (PDF)')),
                ('lettre_motivation', models.FileField(upload_to='lettres/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Lettre de motivation (PDF)')),
                ('diplome', models.FileField(upload_to='diplomes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Diplôme (PDF)')),
                ('photo', models.ImageField(upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name="Photo d'identité (JPG/PNG)")),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
    ]
